// Generated by assets/bot-avatars/science/generate-ios.py. Do not edit.
// Source SHA-256: 9324e397b3c5d27dd693bac25f5a776d451fb7ad941f7567f21446e79fc63c3a
import SwiftUI
import WonderPairing

enum ScienceAvatarGeometry {
    static func layers(for shape: ScienceAvatarShape) -> [ScienceAvatarVectorLayer] {
        switch shape {
        case .sun: sun
        case .orbit: orbit
        case .nova: nova
        case .comet: comet
        case .prism: prism
        case .atom: atom
        case .luna: luna
        }
    }

    static func groupLayers(for shape: ScienceAvatarShape) -> [ScienceAvatarVectorLayer] {
        switch shape {
        case .sun: sunGroup
        case .orbit: orbitGroup
        case .nova: novaGroup
        case .comet: cometGroup
        case .prism: prismGroup
        case .atom: atomGroup
        case .luna: lunaGroup
        }
    }

    private static func grouped(_ layers: [ScienceAvatarVectorLayer]) -> [ScienceAvatarVectorLayer] {
        let placements: [(CGFloat, CGFloat, CGFloat)] = [
            (0, 0, 0.62),
            (97.28, 0, 0.62),
            (48.64, 97.28, 0.62),
        ]
        return placements.flatMap { x, y, scale in
            let transform = CGAffineTransform(a: scale, b: 0, c: 0, d: scale, tx: x, ty: y)
            return layers.map { layer in
                ScienceAvatarVectorLayer(path: layer.path.applying(transform),
                    fill: layer.fill, stroke: layer.stroke, lineWidth: layer.lineWidth * scale,
                    lineCap: layer.lineCap, lineJoin: layer.lineJoin, opacity: layer.opacity)
            }
        }
    }

    private static let sunGroup = grouped(sun)

    private static let orbitGroup = grouped(orbit)

    private static let novaGroup = grouped(nova)

    private static let cometGroup = grouped(comet)

    private static let prismGroup = grouped(prism)

    private static let atomGroup = grouped(atom)

    private static let lunaGroup = grouped(luna)

    private static let sun: [ScienceAvatarVectorLayer] = [
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 128, y: 69.2))
                path.addLine(to: CGPoint(x: 128, y: 89.2))
                path.move(to: CGPoint(x: 63, y: 96.5))
                path.addLine(to: CGPoint(x: 75, y: 108.8))
                path.move(to: CGPoint(x: 181, y: 108.8))
                path.addLine(to: CGPoint(x: 193, y: 96.5))
                path.move(to: CGPoint(x: 29.8, y: 162.4))
                path.addLine(to: CGPoint(x: 46.8, y: 162.4))
                path.move(to: CGPoint(x: 209.2, y: 162.4))
                path.addLine(to: CGPoint(x: 226.2, y: 162.4))
                return path
            }(), fill: nil, stroke: .body, lineWidth: 13.2, lineCap: .round, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 62.3, y: 179.7))
                path.addLine(to: CGPoint(x: 62.3, y: 171.6))
                path.addCurve(to: CGPoint(x: 81.543085, y: 125.143085), control1: CGPoint(x: 62.3, y: 154.175277), control2: CGPoint(x: 69.221945, y: 137.464225))
                path.addCurve(to: CGPoint(x: 128, y: 105.900001), control1: CGPoint(x: 93.864225, y: 112.821946), control2: CGPoint(x: 110.575277, y: 105.900001))
                path.addCurve(to: CGPoint(x: 174.456915, y: 125.143085), control1: CGPoint(x: 145.424723, y: 105.900001), control2: CGPoint(x: 162.135775, y: 112.821946))
                path.addCurve(to: CGPoint(x: 193.7, y: 171.6), control1: CGPoint(x: 186.778055, y: 137.464225), control2: CGPoint(x: 193.7, y: 154.175277))
                path.addLine(to: CGPoint(x: 193.7, y: 179.7))
                path.addCurve(to: CGPoint(x: 192.788973, y: 183.1), control1: CGPoint(x: 193.7, y: 180.893649), control2: CGPoint(x: 193.385797, y: 182.066269))
                path.addCurve(to: CGPoint(x: 190.3, y: 185.588973), control1: CGPoint(x: 192.192148, y: 184.133731), control2: CGPoint(x: 191.333731, y: 184.992148))
                path.addCurve(to: CGPoint(x: 186.9, y: 186.5), control1: CGPoint(x: 189.266269, y: 186.185797), control2: CGPoint(x: 188.093649, y: 186.5))
                path.addLine(to: CGPoint(x: 69.1, y: 186.5))
                path.addCurve(to: CGPoint(x: 65.7, y: 185.588973), control1: CGPoint(x: 67.906351, y: 186.5), control2: CGPoint(x: 66.733731, y: 186.185797))
                path.addCurve(to: CGPoint(x: 63.211027, y: 183.1), control1: CGPoint(x: 64.666269, y: 184.992148), control2: CGPoint(x: 63.807852, y: 184.133731))
                path.addCurve(to: CGPoint(x: 62.3, y: 179.7), control1: CGPoint(x: 62.614203, y: 182.066269), control2: CGPoint(x: 62.3, y: 180.893649))
                path.closeSubpath()
                return path
            }(), fill: .body, stroke: nil, lineWidth: 1, lineCap: .butt, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 62.3, y: 171.5))
                path.addCurve(to: CGPoint(x: 193.7, y: 166.5), control1: CGPoint(x: 98.3, y: 182.5), control2: CGPoint(x: 150.3, y: 181.5))
                path.addLine(to: CGPoint(x: 193.7, y: 179.7))
                path.addCurve(to: CGPoint(x: 192.788973, y: 183.1), control1: CGPoint(x: 193.7, y: 180.893649), control2: CGPoint(x: 193.385797, y: 182.066269))
                path.addCurve(to: CGPoint(x: 190.3, y: 185.588973), control1: CGPoint(x: 192.192148, y: 184.133731), control2: CGPoint(x: 191.333731, y: 184.992148))
                path.addCurve(to: CGPoint(x: 186.9, y: 186.5), control1: CGPoint(x: 189.266269, y: 186.185797), control2: CGPoint(x: 188.093649, y: 186.5))
                path.addLine(to: CGPoint(x: 69.1, y: 186.5))
                path.addCurve(to: CGPoint(x: 65.7, y: 185.588973), control1: CGPoint(x: 67.906351, y: 186.5), control2: CGPoint(x: 66.733731, y: 186.185797))
                path.addCurve(to: CGPoint(x: 63.211027, y: 183.1), control1: CGPoint(x: 64.666269, y: 184.992148), control2: CGPoint(x: 63.807852, y: 184.133731))
                path.addCurve(to: CGPoint(x: 62.3, y: 179.7), control1: CGPoint(x: 62.614203, y: 182.066269), control2: CGPoint(x: 62.3, y: 180.893649))
                path.closeSubpath()
                return path
            }(), fill: .shadow, stroke: nil, lineWidth: 1, lineCap: .butt, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.addRoundedRect(in: CGRect(x: 96.5, y: 142.8, width: 11.2, height: 19.7), cornerSize: CGSize(width: 5.6, height: 5.6))
                return path
            }(), fill: .ink, stroke: nil, lineWidth: 1, lineCap: .butt, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.addRoundedRect(in: CGRect(x: 148.4, y: 142.8, width: 11.2, height: 19.7), cornerSize: CGSize(width: 5.6, height: 5.6))
                return path
            }(), fill: .ink, stroke: nil, lineWidth: 1, lineCap: .butt, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 121.5, y: 165.4))
                path.addQuadCurve(to: CGPoint(x: 134.5, y: 165.4), control: CGPoint(x: 128, y: 172.1))
                return path
            }(), fill: nil, stroke: .ink, lineWidth: 5.5, lineCap: .round, lineJoin: .miter, opacity: 1)
    ]

    private static let orbit: [ScienceAvatarVectorLayer] = [
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 32.662, y: 180.577))
                path.addCurve(to: CGPoint(x: 49.992424, y: 145.557732), control1: CGPoint(x: 28.688693, y: 172.778715), control2: CGPoint(x: 34.922633, y: 160.181907))
                path.addCurve(to: CGPoint(x: 113.018628, y: 102.596529), control1: CGPoint(x: 65.062215, y: 130.933557), control2: CGPoint(x: 87.733419, y: 115.47995))
                path.addCurve(to: CGPoint(x: 184.820717, y: 76.85948), control1: CGPoint(x: 138.303838, y: 89.713107), control2: CGPoint(x: 164.131821, y: 80.455214))
                path.addCurve(to: CGPoint(x: 223.338, y: 83.423), control1: CGPoint(x: 205.509612, y: 73.263746), control2: CGPoint(x: 219.364693, y: 75.624715))
                return path
            }(), fill: nil, stroke: .shadow, lineWidth: 14, lineCap: .butt, lineJoin: .round, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 32.662, y: 180.577))
                path.addCurve(to: CGPoint(x: 49.992424, y: 145.557732), control1: CGPoint(x: 28.688693, y: 172.778715), control2: CGPoint(x: 34.922633, y: 160.181907))
                path.addCurve(to: CGPoint(x: 113.018628, y: 102.596529), control1: CGPoint(x: 65.062215, y: 130.933557), control2: CGPoint(x: 87.733419, y: 115.47995))
                path.addCurve(to: CGPoint(x: 184.820717, y: 76.85948), control1: CGPoint(x: 138.303838, y: 89.713107), control2: CGPoint(x: 164.131821, y: 80.455214))
                path.addCurve(to: CGPoint(x: 223.338, y: 83.423), control1: CGPoint(x: 205.509612, y: 73.263746), control2: CGPoint(x: 219.364693, y: 75.624715))
                return path
            }(), fill: nil, stroke: .accent, lineWidth: 11, lineCap: .butt, lineJoin: .round, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.addEllipse(in: CGRect(x: 53, y: 51, width: 150, height: 150))
                return path
            }(), fill: .body, stroke: nil, lineWidth: 1, lineCap: .butt, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 64.396, y: 165.744))
                path.addCurve(to: CGPoint(x: 202.817, y: 120.768), control1: CGPoint(x: 105, y: 184), control2: CGPoint(x: 168, y: 174))
                path.addCurve(to: CGPoint(x: 190.177736, y: 167.939448), control1: CGPoint(x: 203.984444, y: 137.461554), control2: CGPoint(x: 199.535391, y: 154.066022))
                path.addCurve(to: CGPoint(x: 151.176143, y: 197.329451), control1: CGPoint(x: 180.820081, y: 181.812875), control2: CGPoint(x: 167.091423, y: 192.158229))
                path.addCurve(to: CGPoint(x: 102.348178, y: 196.477186), control1: CGPoint(x: 135.260863, y: 202.500672), control2: CGPoint(x: 118.073297, y: 202.200673))
                path.addCurve(to: CGPoint(x: 64.396, y: 165.744), control1: CGPoint(x: 86.623059, y: 190.7537), control2: CGPoint(x: 73.263797, y: 179.935541))
                path.closeSubpath()
                return path
            }(), fill: .shadow, stroke: nil, lineWidth: 1, lineCap: .butt, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.addEllipse(in: CGRect(x: 89, y: 71, width: 24, height: 12))
                path = path.applying(CGAffineTransform(a: 0.891007, b: -0.45399, c: 0.45399, d: 0.891007, tx: -23.948927, ty: 54.245538))
                return path
            }(), fill: .accent, stroke: nil, lineWidth: 1, lineCap: .butt, lineJoin: .miter, opacity: 0.6),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 32.662, y: 180.577))
                path.addCurve(to: CGPoint(x: 71.179283, y: 187.14052), control1: CGPoint(x: 36.635307, y: 188.375285), control2: CGPoint(x: 50.490388, y: 190.736254))
                path.addCurve(to: CGPoint(x: 142.981372, y: 161.403471), control1: CGPoint(x: 91.868179, y: 183.544786), control2: CGPoint(x: 117.696162, y: 174.286893))
                path.addCurve(to: CGPoint(x: 206.007576, y: 118.442268), control1: CGPoint(x: 168.266581, y: 148.52005), control2: CGPoint(x: 190.937785, y: 133.066443))
                path.addCurve(to: CGPoint(x: 223.338, y: 83.423), control1: CGPoint(x: 221.077367, y: 103.818093), control2: CGPoint(x: 227.311307, y: 91.221285))
                return path
            }(), fill: nil, stroke: .shadow, lineWidth: 14, lineCap: .butt, lineJoin: .round, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 32.009, y: 178.972))
                path.addCurve(to: CGPoint(x: 57.56931, y: 188.704444), control1: CGPoint(x: 34.186285, y: 185.938204), control2: CGPoint(x: 43.16334, y: 189.356343))
                path.addCurve(to: CGPoint(x: 111.790706, y: 175.361721), control1: CGPoint(x: 71.975279, y: 188.052546), control2: CGPoint(x: 91.018415, y: 183.366438))
                path.addCurve(to: CGPoint(x: 172.608344, y: 144.373516), control1: CGPoint(x: 132.562997, y: 167.357004), control2: CGPoint(x: 153.922804, y: 156.473614))
                path.addCurve(to: CGPoint(x: 215.273105, y: 108.350164), control1: CGPoint(x: 191.293884, y: 132.273419), control2: CGPoint(x: 206.278206, y: 119.621631))
                path.addCurve(to: CGPoint(x: 222.423, y: 81.951), control1: CGPoint(x: 224.268004, y: 97.078697), control2: CGPoint(x: 226.779124, y: 87.807027))
                return path
            }(), fill: nil, stroke: .accent, lineWidth: 11, lineCap: .butt, lineJoin: .round, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.addRoundedRect(in: CGRect(x: 98.4, y: 97.2, width: 11.2, height: 17.6), cornerSize: CGSize(width: 5.6, height: 5.6))
                path = path.applying(CGAffineTransform(a: 0.978148, b: -0.207912, c: 0.207912, d: 0.978148, tx: -20.160588, ty: 28.184814))
                return path
            }(), fill: .ink, stroke: nil, lineWidth: 1, lineCap: .butt, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.addRoundedRect(in: CGRect(x: 138.4, y: 97.2, width: 11.2, height: 17.6), cornerSize: CGSize(width: 5.6, height: 5.6))
                path = path.applying(CGAffineTransform(a: 0.978148, b: -0.207912, c: 0.207912, d: 0.978148, tx: -20.160588, ty: 28.184814))
                return path
            }(), fill: .ink, stroke: nil, lineWidth: 1, lineCap: .butt, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 116, y: 128))
                path.addQuadCurve(to: CGPoint(x: 132, y: 128), control: CGPoint(x: 124, y: 137))
                path = path.applying(CGAffineTransform(a: 0.978148, b: -0.207912, c: 0.207912, d: 0.978148, tx: -20.160588, ty: 28.184814))
                return path
            }(), fill: nil, stroke: .ink, lineWidth: 5.5, lineCap: .round, lineJoin: .round, opacity: 1)
    ]

    private static let nova: [ScienceAvatarVectorLayer] = [
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 128, y: 22))
                path.addCurve(to: CGPoint(x: 158, y: 98), control1: CGPoint(x: 134, y: 22), control2: CGPoint(x: 136, y: 76))
                path.addCurve(to: CGPoint(x: 234, y: 128), control1: CGPoint(x: 180, y: 120), control2: CGPoint(x: 234, y: 122))
                path.addCurve(to: CGPoint(x: 158, y: 158), control1: CGPoint(x: 234, y: 134), control2: CGPoint(x: 180, y: 136))
                path.addCurve(to: CGPoint(x: 128, y: 234), control1: CGPoint(x: 136, y: 180), control2: CGPoint(x: 134, y: 234))
                path.addCurve(to: CGPoint(x: 98, y: 158), control1: CGPoint(x: 122, y: 234), control2: CGPoint(x: 120, y: 180))
                path.addCurve(to: CGPoint(x: 22, y: 128), control1: CGPoint(x: 76, y: 136), control2: CGPoint(x: 22, y: 134))
                path.addCurve(to: CGPoint(x: 98, y: 98), control1: CGPoint(x: 22, y: 122), control2: CGPoint(x: 76, y: 120))
                path.addCurve(to: CGPoint(x: 128, y: 22), control1: CGPoint(x: 120, y: 76), control2: CGPoint(x: 122, y: 22))
                path.closeSubpath()
                return path
            }(), fill: .body, stroke: nil, lineWidth: 1, lineCap: .butt, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 22, y: 128))
                path.addLine(to: CGPoint(x: 234, y: 128))
                path.addCurve(to: CGPoint(x: 158, y: 158), control1: CGPoint(x: 234, y: 134), control2: CGPoint(x: 180, y: 136))
                path.addCurve(to: CGPoint(x: 128, y: 234), control1: CGPoint(x: 136, y: 180), control2: CGPoint(x: 134, y: 234))
                path.addCurve(to: CGPoint(x: 98, y: 158), control1: CGPoint(x: 122, y: 234), control2: CGPoint(x: 120, y: 180))
                path.addCurve(to: CGPoint(x: 22, y: 128), control1: CGPoint(x: 76, y: 136), control2: CGPoint(x: 22, y: 134))
                path.closeSubpath()
                return path
            }(), fill: .shadow, stroke: nil, lineWidth: 1, lineCap: .butt, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 128, y: 34))
                path.addLine(to: CGPoint(x: 141, y: 115))
                path.addLine(to: CGPoint(x: 222, y: 128))
                path.addLine(to: CGPoint(x: 141, y: 141))
                path.addLine(to: CGPoint(x: 128, y: 222))
                path.addLine(to: CGPoint(x: 115, y: 141))
                path.addLine(to: CGPoint(x: 34, y: 128))
                path.addLine(to: CGPoint(x: 115, y: 115))
                path.closeSubpath()
                return path
            }(), fill: .accent, stroke: nil, lineWidth: 1, lineCap: .butt, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.addEllipse(in: CGRect(x: 88.5, y: 88.5, width: 79, height: 79))
                return path
            }(), fill: .accent, stroke: nil, lineWidth: 1, lineCap: .butt, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.addRoundedRect(in: CGRect(x: 106.4, y: 110.4, width: 11.2, height: 17.6), cornerSize: CGSize(width: 5.6, height: 5.6))
                return path
            }(), fill: .ink, stroke: nil, lineWidth: 1, lineCap: .butt, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.addRoundedRect(in: CGRect(x: 138.4, y: 110.4, width: 11.2, height: 17.6), cornerSize: CGSize(width: 5.6, height: 5.6))
                return path
            }(), fill: .ink, stroke: nil, lineWidth: 1, lineCap: .butt, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 120, y: 138))
                path.addQuadCurve(to: CGPoint(x: 136, y: 138), control: CGPoint(x: 128, y: 147))
                return path
            }(), fill: nil, stroke: .ink, lineWidth: 5.5, lineCap: .round, lineJoin: .round, opacity: 1)
    ]

    private static let comet: [ScienceAvatarVectorLayer] = [
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 43, y: 123))
                path.addCurve(to: CGPoint(x: 127, y: 59), control1: CGPoint(x: 65, y: 95), control2: CGPoint(x: 100, y: 90))
                path.addCurve(to: CGPoint(x: 196, y: 22), control1: CGPoint(x: 154, y: 28), control2: CGPoint(x: 184, y: 13))
                path.addCurve(to: CGPoint(x: 178, y: 73), control1: CGPoint(x: 208, y: 31), control2: CGPoint(x: 178, y: 73))
                path.addCurve(to: CGPoint(x: 233, y: 43), control1: CGPoint(x: 178, y: 73), control2: CGPoint(x: 222, y: 34))
                path.addCurve(to: CGPoint(x: 206, y: 100), control1: CGPoint(x: 244, y: 52), control2: CGPoint(x: 206, y: 100))
                path.addCurve(to: CGPoint(x: 236, y: 95), control1: CGPoint(x: 206, y: 100), control2: CGPoint(x: 231, y: 85))
                path.addCurve(to: CGPoint(x: 178, y: 174), control1: CGPoint(x: 243, y: 109), control2: CGPoint(x: 209, y: 146))
                path.addCurve(to: CGPoint(x: 87, y: 218), control1: CGPoint(x: 149, y: 200), control2: CGPoint(x: 120, y: 222))
                path.addCurve(to: CGPoint(x: 43, y: 123), control1: CGPoint(x: 39, y: 212), control2: CGPoint(x: 21, y: 157))
                path.closeSubpath()
                path = path.applying(CGAffineTransform(a: 0.93, b: 0, c: 0, d: 0.93, tx: 0, ty: 0))
                path = path.applying(CGAffineTransform(a: 1, b: 0, c: 0, d: 1, tx: 8.96, ty: 8.96))
                return path
            }(), fill: .shadow, stroke: nil, lineWidth: 0.93, lineCap: .butt, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 48, y: 123))
                path.addCurve(to: CGPoint(x: 167, y: 55), control1: CGPoint(x: 79, y: 91), control2: CGPoint(x: 127, y: 93))
                path.addCurve(to: CGPoint(x: 144, y: 104), control1: CGPoint(x: 163, y: 74), control2: CGPoint(x: 143, y: 98))
                path.addCurve(to: CGPoint(x: 180, y: 95), control1: CGPoint(x: 147, y: 112), control2: CGPoint(x: 174, y: 91))
                path.addCurve(to: CGPoint(x: 151, y: 139), control1: CGPoint(x: 190, y: 101), control2: CGPoint(x: 149, y: 132))
                path.addCurve(to: CGPoint(x: 179, y: 136), control1: CGPoint(x: 157, y: 145), control2: CGPoint(x: 173, y: 132))
                path.addCurve(to: CGPoint(x: 116, y: 206), control1: CGPoint(x: 189, y: 143), control2: CGPoint(x: 144, y: 195))
                path.addCurve(to: CGPoint(x: 48, y: 123), control1: CGPoint(x: 64, y: 228), control2: CGPoint(x: 15, y: 170))
                path.closeSubpath()
                path = path.applying(CGAffineTransform(a: 0.93, b: 0, c: 0, d: 0.93, tx: 0, ty: 0))
                path = path.applying(CGAffineTransform(a: 1, b: 0, c: 0, d: 1, tx: 8.96, ty: 8.96))
                return path
            }(), fill: .body, stroke: nil, lineWidth: 0.93, lineCap: .butt, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.addEllipse(in: CGRect(x: 34, y: 98, width: 110, height: 118))
                path = path.applying(CGAffineTransform(a: 0.848048, b: 0.529919, c: -0.529919, d: 0.848048, tx: 96.721044, ty: -23.306366))
                path = path.applying(CGAffineTransform(a: 0.93, b: 0, c: 0, d: 0.93, tx: 0, ty: 0))
                path = path.applying(CGAffineTransform(a: 1, b: 0, c: 0, d: 1, tx: 8.96, ty: 8.96))
                return path
            }(), fill: .accent, stroke: .body, lineWidth: 4.185, lineCap: .butt, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.addRoundedRect(in: CGRect(x: 66.4, y: 140.2, width: 11.2, height: 17.6), cornerSize: CGSize(width: 5.6, height: 5.6))
                path = path.applying(CGAffineTransform(a: 0.913545, b: 0.406737, c: -0.406737, d: 0.913545, tx: 71.552107, ty: -22.626198))
                path = path.applying(CGAffineTransform(a: 1, b: 0, c: 0, d: 1, tx: 2.73, ty: -2.03))
                return path
            }(), fill: .ink, stroke: nil, lineWidth: 1, lineCap: .butt, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.addRoundedRect(in: CGRect(x: 100.4, y: 140.2, width: 11.2, height: 17.6), cornerSize: CGSize(width: 5.6, height: 5.6))
                path = path.applying(CGAffineTransform(a: 0.913545, b: 0.406737, c: -0.406737, d: 0.913545, tx: 71.552107, ty: -22.626198))
                path = path.applying(CGAffineTransform(a: 1, b: 0, c: 0, d: 1, tx: 2.73, ty: -2.03))
                return path
            }(), fill: .ink, stroke: nil, lineWidth: 1, lineCap: .butt, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 81, y: 173))
                path.addQuadCurve(to: CGPoint(x: 97, y: 173), control: CGPoint(x: 89, y: 182))
                path = path.applying(CGAffineTransform(a: 0.913545, b: 0.406737, c: -0.406737, d: 0.913545, tx: 71.552107, ty: -22.626198))
                path = path.applying(CGAffineTransform(a: 1, b: 0, c: 0, d: 1, tx: 2.73, ty: -2.03))
                return path
            }(), fill: nil, stroke: .ink, lineWidth: 5.5, lineCap: .round, lineJoin: .round, opacity: 1)
    ]

    private static let prism: [ScienceAvatarVectorLayer] = [
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 128, y: 26))
                path.addQuadCurve(to: CGPoint(x: 132, y: 30), control: CGPoint(x: 130, y: 26))
                path.addLine(to: CGPoint(x: 224, y: 190))
                path.addQuadCurve(to: CGPoint(x: 220, y: 200), control: CGPoint(x: 228, y: 197))
                path.addLine(to: CGPoint(x: 132, y: 228))
                path.addQuadCurve(to: CGPoint(x: 124, y: 228), control: CGPoint(x: 128, y: 230))
                path.addLine(to: CGPoint(x: 36, y: 200))
                path.addQuadCurve(to: CGPoint(x: 32, y: 190), control: CGPoint(x: 28, y: 197))
                path.addLine(to: CGPoint(x: 124, y: 30))
                path.addQuadCurve(to: CGPoint(x: 128, y: 26), control: CGPoint(x: 126, y: 26))
                path.closeSubpath()
                return path
            }(), fill: .body, stroke: nil, lineWidth: 1, lineCap: .butt, lineJoin: .round, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 128, y: 26))
                path.addQuadCurve(to: CGPoint(x: 124, y: 30), control: CGPoint(x: 126, y: 26))
                path.addLine(to: CGPoint(x: 32, y: 190))
                path.addQuadCurve(to: CGPoint(x: 36, y: 200), control: CGPoint(x: 28, y: 197))
                path.addLine(to: CGPoint(x: 86, y: 160))
                path.closeSubpath()
                return path
            }(), fill: .shadow, stroke: nil, lineWidth: 1, lineCap: .butt, lineJoin: .round, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 128, y: 26))
                path.addQuadCurve(to: CGPoint(x: 132, y: 30), control: CGPoint(x: 130, y: 26))
                path.addLine(to: CGPoint(x: 224, y: 190))
                path.addQuadCurve(to: CGPoint(x: 220, y: 200), control: CGPoint(x: 228, y: 197))
                path.addLine(to: CGPoint(x: 170, y: 160))
                path.closeSubpath()
                return path
            }(), fill: .accent, stroke: nil, lineWidth: 1, lineCap: .butt, lineJoin: .round, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 86, y: 160))
                path.addLine(to: CGPoint(x: 170, y: 160))
                path.addLine(to: CGPoint(x: 132, y: 228))
                path.addQuadCurve(to: CGPoint(x: 124, y: 228), control: CGPoint(x: 128, y: 230))
                path.closeSubpath()
                return path
            }(), fill: .shadow, stroke: nil, lineWidth: 1, lineCap: .butt, lineJoin: .round, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 128, y: 44))
                path.addLine(to: CGPoint(x: 142, y: 103))
                path.addLine(to: CGPoint(x: 131, y: 90))
                path.closeSubpath()
                return path
            }(), fill: .accent, stroke: nil, lineWidth: 1, lineCap: .butt, lineJoin: .round, opacity: 0.45),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.addRoundedRect(in: CGRect(x: 106.4, y: 118.2, width: 11.2, height: 17.6), cornerSize: CGSize(width: 5.6, height: 5.6))
                return path
            }(), fill: .ink, stroke: nil, lineWidth: 1, lineCap: .butt, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.addRoundedRect(in: CGRect(x: 138.4, y: 118.2, width: 11.2, height: 17.6), cornerSize: CGSize(width: 5.6, height: 5.6))
                return path
            }(), fill: .ink, stroke: nil, lineWidth: 1, lineCap: .butt, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 120, y: 145))
                path.addQuadCurve(to: CGPoint(x: 136, y: 145), control: CGPoint(x: 128, y: 154))
                return path
            }(), fill: nil, stroke: .ink, lineWidth: 5.5, lineCap: .round, lineJoin: .round, opacity: 1)
    ]

    private static let atom: [ScienceAvatarVectorLayer] = [
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 49.014, y: 54.344))
                path.addCurve(to: CGPoint(x: 91.445696, y: 55.262651), control1: CGPoint(x: 56.260326, y: 46.602288), control2: CGPoint(x: 71.522462, y: 46.932715))
                path.addCurve(to: CGPoint(x: 155.261781, y: 98.76637), control1: CGPoint(x: 111.36893, y: 63.592588), control2: CGPoint(x: 134.322756, y: 79.240317))
                path.addCurve(to: CGPoint(x: 203.110549, y: 159.392325), control1: CGPoint(x: 176.200807, y: 118.292423), control2: CGPoint(x: 193.411394, y: 140.098801))
                path.addCurve(to: CGPoint(x: 206.986, y: 201.656), control1: CGPoint(x: 212.809704, y: 178.685849), control2: CGPoint(x: 214.203654, y: 193.887551))
                return path
            }(), fill: nil, stroke: .shadow, lineWidth: 14, lineCap: .butt, lineJoin: .round, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 49.014, y: 54.344))
                path.addCurve(to: CGPoint(x: 91.445696, y: 55.262651), control1: CGPoint(x: 56.260326, y: 46.602288), control2: CGPoint(x: 71.522462, y: 46.932715))
                path.addCurve(to: CGPoint(x: 155.261781, y: 98.76637), control1: CGPoint(x: 111.36893, y: 63.592588), control2: CGPoint(x: 134.322756, y: 79.240317))
                path.addCurve(to: CGPoint(x: 203.110549, y: 159.392325), control1: CGPoint(x: 176.200807, y: 118.292423), control2: CGPoint(x: 193.411394, y: 140.098801))
                path.addCurve(to: CGPoint(x: 206.986, y: 201.656), control1: CGPoint(x: 212.809704, y: 178.685849), control2: CGPoint(x: 214.203654, y: 193.887551))
                return path
            }(), fill: nil, stroke: .accent, lineWidth: 11, lineCap: .butt, lineJoin: .round, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 49.014, y: 201.656))
                path.addCurve(to: CGPoint(x: 52.889451, y: 159.392325), control1: CGPoint(x: 41.796346, y: 193.887551), control2: CGPoint(x: 43.190296, y: 178.685849))
                path.addCurve(to: CGPoint(x: 100.738219, y: 98.76637), control1: CGPoint(x: 62.588606, y: 140.098801), control2: CGPoint(x: 79.799193, y: 118.292423))
                path.addCurve(to: CGPoint(x: 164.554304, y: 55.262651), control1: CGPoint(x: 121.677244, y: 79.240317), control2: CGPoint(x: 144.63107, y: 63.592588))
                path.addCurve(to: CGPoint(x: 206.986, y: 54.344), control1: CGPoint(x: 184.477538, y: 46.932715), control2: CGPoint(x: 199.739674, y: 46.602288))
                return path
            }(), fill: nil, stroke: .shadow, lineWidth: 14, lineCap: .butt, lineJoin: .round, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 49.014, y: 201.656))
                path.addCurve(to: CGPoint(x: 52.889451, y: 159.392325), control1: CGPoint(x: 41.796346, y: 193.887551), control2: CGPoint(x: 43.190296, y: 178.685849))
                path.addCurve(to: CGPoint(x: 100.738219, y: 98.76637), control1: CGPoint(x: 62.588606, y: 140.098801), control2: CGPoint(x: 79.799193, y: 118.292423))
                path.addCurve(to: CGPoint(x: 164.554304, y: 55.262651), control1: CGPoint(x: 121.677244, y: 79.240317), control2: CGPoint(x: 144.63107, y: 63.592588))
                path.addCurve(to: CGPoint(x: 206.986, y: 54.344), control1: CGPoint(x: 184.477538, y: 46.932715), control2: CGPoint(x: 199.739674, y: 46.602288))
                return path
            }(), fill: nil, stroke: .accent, lineWidth: 11, lineCap: .butt, lineJoin: .round, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.addEllipse(in: CGRect(x: 67, y: 63, width: 122, height: 122))
                return path
            }(), fill: .body, stroke: nil, lineWidth: 1, lineCap: .butt, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 76.269, y: 156.325))
                path.addCurve(to: CGPoint(x: 188.851, y: 119.745), control1: CGPoint(x: 109, y: 173), control2: CGPoint(x: 157, y: 163))
                path.addCurve(to: CGPoint(x: 178.570568, y: 158.11043), control1: CGPoint(x: 189.800221, y: 133.322253), control2: CGPoint(x: 186.181488, y: 146.82696))
                path.addCurve(to: CGPoint(x: 146.849518, y: 182.013747), control1: CGPoint(x: 170.959648, y: 169.393901), control2: CGPoint(x: 159.793775, y: 177.807915))
                path.addCurve(to: CGPoint(x: 107.136634, y: 181.320653), control1: CGPoint(x: 133.905261, y: 186.219578), control2: CGPoint(x: 119.926247, y: 185.975608))
                path.addCurve(to: CGPoint(x: 76.269, y: 156.325), control1: CGPoint(x: 94.347021, y: 176.665698), control2: CGPoint(x: 83.481553, y: 167.867179))
                path.closeSubpath()
                return path
            }(), fill: .shadow, stroke: nil, lineWidth: 1, lineCap: .butt, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 93, y: 91))
                path.addQuadCurve(to: CGPoint(x: 117, y: 79), control: CGPoint(x: 104, y: 80))
                return path
            }(), fill: nil, stroke: .accent, lineWidth: 6, lineCap: .round, lineJoin: .miter, opacity: 0.6),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 49.014, y: 54.344))
                path.addCurve(to: CGPoint(x: 52.889451, y: 96.607675), control1: CGPoint(x: 41.796346, y: 62.112449), control2: CGPoint(x: 43.190296, y: 77.314151))
                path.addCurve(to: CGPoint(x: 100.738219, y: 157.23363), control1: CGPoint(x: 62.588606, y: 115.901199), control2: CGPoint(x: 79.799193, y: 137.707577))
                path.addCurve(to: CGPoint(x: 164.554304, y: 200.737349), control1: CGPoint(x: 121.677244, y: 176.759683), control2: CGPoint(x: 144.63107, y: 192.407412))
                path.addCurve(to: CGPoint(x: 206.986, y: 201.656), control1: CGPoint(x: 184.477538, y: 209.067285), control2: CGPoint(x: 199.739674, y: 209.397712))
                return path
            }(), fill: nil, stroke: .shadow, lineWidth: 14, lineCap: .butt, lineJoin: .round, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 50.55, y: 52.914))
                path.addCurve(to: CGPoint(x: 47.339528, y: 83.524128), control1: CGPoint(x: 43.699646, y: 58.451218), control2: CGPoint(x: 42.572095, y: 69.201809))
                path.addCurve(to: CGPoint(x: 76.952575, y: 132.2326), control1: CGPoint(x: 52.106961, y: 97.846447), control2: CGPoint(x: 62.507368, y: 114.953363))
                path.addCurve(to: CGPoint(x: 127.3387, y: 179.218469), control1: CGPoint(x: 91.397783, y: 149.511837), control2: CGPoint(x: 109.093908, y: 166.013757))
                path.addCurve(to: CGPoint(x: 177.994267, y: 205.361768), control1: CGPoint(x: 145.583491, y: 192.423181), control2: CGPoint(x: 163.374247, y: 201.604976))
                path.addCurve(to: CGPoint(x: 208.306, y: 200.024), control1: CGPoint(x: 192.614287, y: 209.118559), control2: CGPoint(x: 203.260079, y: 207.24388))
                return path
            }(), fill: nil, stroke: .accent, lineWidth: 11, lineCap: .butt, lineJoin: .round, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 49.014, y: 201.656))
                path.addCurve(to: CGPoint(x: 91.445696, y: 200.737349), control1: CGPoint(x: 56.260326, y: 209.397712), control2: CGPoint(x: 71.522462, y: 209.067285))
                path.addCurve(to: CGPoint(x: 155.261781, y: 157.23363), control1: CGPoint(x: 111.36893, y: 192.407412), control2: CGPoint(x: 134.322756, y: 176.759683))
                path.addCurve(to: CGPoint(x: 203.110549, y: 96.607675), control1: CGPoint(x: 176.200807, y: 137.707577), control2: CGPoint(x: 193.411394, y: 115.901199))
                path.addCurve(to: CGPoint(x: 206.986, y: 54.344), control1: CGPoint(x: 212.809704, y: 77.314151), control2: CGPoint(x: 214.203654, y: 62.112449))
                return path
            }(), fill: nil, stroke: .shadow, lineWidth: 14, lineCap: .butt, lineJoin: .round, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 47.694, y: 200.024))
                path.addCurve(to: CGPoint(x: 78.005733, y: 205.361768), control1: CGPoint(x: 52.739921, y: 207.24388), control2: CGPoint(x: 63.385713, y: 209.118559))
                path.addCurve(to: CGPoint(x: 128.6613, y: 179.218469), control1: CGPoint(x: 92.625753, y: 201.604976), control2: CGPoint(x: 110.416509, y: 192.423181))
                path.addCurve(to: CGPoint(x: 179.047425, y: 132.2326), control1: CGPoint(x: 146.906092, y: 166.013757), control2: CGPoint(x: 164.602217, y: 149.511837))
                path.addCurve(to: CGPoint(x: 208.660472, y: 83.524128), control1: CGPoint(x: 193.492632, y: 114.953363), control2: CGPoint(x: 203.893039, y: 97.846447))
                path.addCurve(to: CGPoint(x: 205.45, y: 52.914), control1: CGPoint(x: 213.427905, y: 69.201809), control2: CGPoint(x: 212.300354, y: 58.451218))
                return path
            }(), fill: nil, stroke: .accent, lineWidth: 11, lineCap: .butt, lineJoin: .round, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.addEllipse(in: CGRect(x: 193.986, y: 41.344, width: 26, height: 26))
                return path
            }(), fill: .body, stroke: .shadow, lineWidth: 3, lineCap: .butt, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.addEllipse(in: CGRect(x: 200.486, y: 47.844, width: 7, height: 7))
                return path
            }(), fill: .accent, stroke: nil, lineWidth: 1, lineCap: .butt, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.addRoundedRect(in: CGRect(x: 103.4, y: 104, width: 11.2, height: 17.6), cornerSize: CGSize(width: 5.6, height: 5.6))
                return path
            }(), fill: .ink, stroke: nil, lineWidth: 1, lineCap: .butt, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.addRoundedRect(in: CGRect(x: 141.4, y: 104, width: 11.2, height: 17.6), cornerSize: CGSize(width: 5.6, height: 5.6))
                return path
            }(), fill: .ink, stroke: nil, lineWidth: 1, lineCap: .butt, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 120, y: 135))
                path.addQuadCurve(to: CGPoint(x: 136, y: 135), control: CGPoint(x: 128, y: 144))
                return path
            }(), fill: nil, stroke: .ink, lineWidth: 5.5, lineCap: .round, lineJoin: .round, opacity: 1)
    ]

    private static let luna: [ScienceAvatarVectorLayer] = [
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 154, y: 25))
                path.addCurve(to: CGPoint(x: 157, y: 33), control1: CGPoint(x: 161, y: 24), control2: CGPoint(x: 163, y: 28))
                path.addCurve(to: CGPoint(x: 140.739649, y: 93.551394), control1: CGPoint(x: 144.153561, y: 50.418606), control2: CGPoint(x: 138.34724, y: 72.040578))
                path.addCurve(to: CGPoint(x: 169.906994, y: 149.05037), control1: CGPoint(x: 143.132058, y: 115.06221), control2: CGPoint(x: 153.547269, y: 134.880041))
                path.addCurve(to: CGPoint(x: 229, y: 170), control1: CGPoint(x: 186.266719, y: 163.220699), control2: CGPoint(x: 207.367923, y: 170.70149))
                path.addCurve(to: CGPoint(x: 233, y: 178), control1: CGPoint(x: 236, y: 168), control2: CGPoint(x: 238, y: 172))
                path.addCurve(to: CGPoint(x: 176.139676, y: 231.502725), control1: CGPoint(x: 221.381551, y: 202.300793), control2: CGPoint(x: 201.101814, y: 221.383013))
                path.addCurve(to: CGPoint(x: 98.074278, y: 232.69922), control1: CGPoint(x: 151.177539, y: 241.622437), control2: CGPoint(x: 123.334824, y: 242.049177))
                path.addCurve(to: CGPoint(x: 39.600994, y: 180.964193), control1: CGPoint(x: 72.813733, y: 223.349262), control2: CGPoint(x: 51.958718, y: 204.897507))
                path.addCurve(to: CGPoint(x: 31.27812, y: 103.334509), control1: CGPoint(x: 27.24327, y: 157.030879), control2: CGPoint(x: 24.274843, y: 129.343565))
                path.addCurve(to: CGPoint(x: 77.455214, y: 40.379652), control1: CGPoint(x: 38.281398, y: 77.325453), control2: CGPoint(x: 54.750867, y: 54.872046))
                path.addCurve(to: CGPoint(x: 154, y: 25), control1: CGPoint(x: 100.159561, y: 25.887258), control2: CGPoint(x: 127.459936, y: 20.401969))
                path.closeSubpath()
                path = path.applying(CGAffineTransform(a: 0.89, b: 0, c: 0, d: 0.89, tx: 0, ty: 0))
                path = path.applying(CGAffineTransform(a: 1, b: 0, c: 0, d: 1, tx: 14.08, ty: 14.08))
                return path
            }(), fill: .body, stroke: nil, lineWidth: 0.89, lineCap: .butt, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 48, y: 167))
                path.addCurve(to: CGPoint(x: 227, y: 180), control1: CGPoint(x: 92, y: 209), control2: CGPoint(x: 157, y: 207))
                path.addCurve(to: CGPoint(x: 169.032944, y: 218.086038), control1: CGPoint(x: 212.390656, y: 198.723371), control2: CGPoint(x: 192.017208, y: 212.109318))
                path.addCurve(to: CGPoint(x: 99.855746, y: 213.061996), control1: CGPoint(x: 146.048681, y: 224.062758), control2: CGPoint(x: 121.735249, y: 222.296978))
                path.addCurve(to: CGPoint(x: 48, y: 167), control1: CGPoint(x: 77.976242, y: 203.827013), control2: CGPoint(x: 59.750712, y: 187.637789))
                path.closeSubpath()
                path = path.applying(CGAffineTransform(a: 0.89, b: 0, c: 0, d: 0.89, tx: 0, ty: 0))
                path = path.applying(CGAffineTransform(a: 1, b: 0, c: 0, d: 1, tx: 14.08, ty: 14.08))
                return path
            }(), fill: .shadow, stroke: nil, lineWidth: 0.89, lineCap: .butt, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.addEllipse(in: CGRect(x: 61, y: 91, width: 24, height: 24))
                path = path.applying(CGAffineTransform(a: 0.89, b: 0, c: 0, d: 0.89, tx: 0, ty: 0))
                path = path.applying(CGAffineTransform(a: 1, b: 0, c: 0, d: 1, tx: 14.08, ty: 14.08))
                return path
            }(), fill: .shadow, stroke: nil, lineWidth: 0.89, lineCap: .butt, lineJoin: .miter, opacity: 1),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.addEllipse(in: CGRect(x: 67.5, y: 92.5, width: 17, height: 17))
                path = path.applying(CGAffineTransform(a: 0.89, b: 0, c: 0, d: 0.89, tx: 0, ty: 0))
                path = path.applying(CGAffineTransform(a: 1, b: 0, c: 0, d: 1, tx: 14.08, ty: 14.08))
                return path
            }(), fill: .accent, stroke: nil, lineWidth: 0.89, lineCap: .butt, lineJoin: .miter, opacity: 0.5),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.addEllipse(in: CGRect(x: 144.5, y: 177.5, width: 13, height: 13))
                path = path.applying(CGAffineTransform(a: 0.89, b: 0, c: 0, d: 0.89, tx: 0, ty: 0))
                path = path.applying(CGAffineTransform(a: 1, b: 0, c: 0, d: 1, tx: 14.08, ty: 14.08))
                return path
            }(), fill: .shadow, stroke: nil, lineWidth: 0.89, lineCap: .butt, lineJoin: .miter, opacity: 0.65),
            ScienceAvatarVectorLayer(path: {
                var path = Path()
                path.move(to: CGPoint(x: 72, y: 142))
                path.addQuadCurve(to: CGPoint(x: 83, y: 142), control: CGPoint(x: 77.5, y: 150))
                path.move(to: CGPoint(x: 104, y: 142))
                path.addQuadCurve(to: CGPoint(x: 115, y: 142), control: CGPoint(x: 109.5, y: 150))
                path.move(to: CGPoint(x: 86, y: 159))
                path.addQuadCurve(to: CGPoint(x: 102, y: 159), control: CGPoint(x: 94, y: 167))
                path = path.applying(CGAffineTransform(a: 0.978148, b: -0.207912, c: 0.207912, d: 0.978148, tx: -28.552598, ty: 22.340178))
                path = path.applying(CGAffineTransform(a: 1, b: 0, c: 0, d: 1, tx: 3.96, ty: -2.09))
                return path
            }(), fill: nil, stroke: .ink, lineWidth: 5.5, lineCap: .round, lineJoin: .round, opacity: 1)
    ]
}
