/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=PushBindings` (hash: f9c41a9845d0fbb5bdbc3af54f35d816)
interface __BaseEnv_PushBindings {
	DB: D1Database;
	IP_RATE_LIMITER: RateLimit;
	APNS_TOPIC: string;
	APNS_ENVIRONMENT: string;
	APNS_KEY_ID: string;
	APNS_TEAM_ID: string;
	APNS_PRIVATE_KEY: string;
	RATE_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_PushBindings {}
}
interface PushBindings extends __BaseEnv_PushBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APNS_TOPIC" | "APNS_ENVIRONMENT" | "APNS_KEY_ID" | "APNS_TEAM_ID" | "APNS_PRIVATE_KEY" | "RATE_SECRET">> {}
}
