ALTER TABLE approvals ADD COLUMN thread_id TEXT NOT NULL DEFAULT '';
ALTER TABLE approvals ADD COLUMN turn_id TEXT NOT NULL DEFAULT '';
ALTER TABLE approvals ADD COLUMN item_id TEXT NOT NULL DEFAULT '';
